export const FETCH_LEARNING_LIST_REQUEST = "FETCH_LEARNING_LIST_REQUEST";
export const FETCH_LEARNING_LIST_SUCCESS = "FETCH_LEARNING_LIST_SUCCESS";
export const FETCH_LEARNING_LIST_FAILURE = "FETCH_LEARNING_LIST_FAILURE";
export const FETCH_LEARNING_REQUEST = "FETCH_LEARNING_REQUEST";
export const FETCH_LEARNING_SUCCESS = "FETCH_LEARNING_SUCCESS";
export const FETCH_LEARNINGS_FAILURE = "FETCH_LEARNINGS_FAILURE";

