export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
